version: '3'

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes:
    mysql:
        driver: local
    redis:
        driver: local
    elasticsearch:
        driver: local

services:

    ### Workspace Utilities ##################################
    workspace:
        build:
            context: ./workspace
            args:
                - LARADOCK_PHP_VERSION=${PHP_VERSION}
                - TZ=${WORKSPACE_TIMEZONE}
                - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
                - SSH_PUBLIC_KEY=${SSH_PUBLIC_KEY}
        volumes:
            - ${APP_CODE_PATH_HOST}:/var/www${APP_CODE_CONTAINER_FLAG}
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
        ports:
            - "${SSH_PORT}:22"
        tty: true
        networks:
            - frontend
            - backend

    ### PHP-FPM ##############################################
    php-fpm:
        build:
            context: ./php-fpm
            args:
                - LARADOCK_PHP_VERSION=${PHP_VERSION}
        volumes:
            - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
            - ${APP_CODE_PATH_HOST}:/var/www${APP_CODE_CONTAINER_FLAG}
        expose:
            - "9000"
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
        environment:
            - FAKETIME="-0"
        depends_on:
            - workspace
        networks:
            - backend

    ### NGINX Server #########################################
    nginx:
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM_CONTAINER=php-fpm
                - PHP_UPSTREAM_PORT=9000
                - CHANGE_SOURCE=false
        volumes:
            - ${APP_CODE_PATH_HOST}:/var/www${APP_CODE_CONTAINER_FLAG}
            - ${DATA_PATH_HOST}/logs/nginx/:/var/log/nginx
            - ./nginx/sites/:/etc/nginx/sites-available
            - ./nginx/ssl/:/etc/nginx/ssl
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php-fpm
        networks:
            - frontend
            - backend

    ### MySQL ################################################
    mysql:
        build: ./mysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - TZ=${WORKSPACE_TIMEZONE}
        volumes:
            - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
            - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        ports:
            - "${MYSQL_PORT}:3306"
        networks:
            - backend

    ### Redis ################################################
    redis:
        build: ./redis
        volumes:
            - ${DATA_PATH_HOST}/redis:/data
        ports:
            - "${REDIS_PORT}:6379"
        networks:
            - backend

    ### REDISWEBUI ################################################
    redis-webui:
        build:
            context: ./redis-webui
        environment:
            - ADMIN_USER=${REDIS_WEBUI_USERNAME}
            - ADMIN_PASS=${REDIS_WEBUI_PASSWORD}
            - REDIS_1_HOST=${REDIS_WEBUI_CONNECT_HOST}
            - REDIS_1_PORT=${REDIS_WEBUI_CONNECT_PORT}
        networks:
            - backend
        ports:
            - "${REDIS_WEBUI_PORT}:80"
        depends_on:
            - redis
